---

- name: Update repositories cache. 
  apt:
    update_cache: yes


- name: Safe system upgrade via aptitude.
  apt: 
    upgrade: safe


- name: Install packages required by Docker.
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - nmap