stages:
  - install
  - build
  - test
  - deploy

variables:
  NODE_VERSION: 15.14.0

before_script:
  - 'echo "Using Node $NODE_VERSION"'
  - 'nvm install $NODE_VERSION'
  - 'nvm use $NODE_VERSION'

install_dependencies:
  stage: install
  image: node:$NODE_VERSION
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

build_project:
  stage: build
  image: node:$NODE_VERSION
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master

test_project:
  stage: test
  image: node:$NODE_VERSION
  script:
    - npm test
  only:
    - master

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache rsync
    - rsync -avz --delete ./build/ vagrant@192.168.56.11:/var/www/myapp/frontend
  only:
    - master