---
- name: Install curl (required for GitLab Runner installation)
  apt:
    name: curl
    state: present

- name: Add GitLab Runner repository
  ansible.builtin.shell:
    cmd: >
      if ! apt-cache policy | grep -q 'gitlab-runner'; then 
        curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
      fi
  args:
  changed_when: false

- name: Install GitLab Runner
  apt:
    name: gitlab-runner
    state: present

- name: Restart GitLab Runner
  ansible.builtin.shell:
    cmd: gitlab-runner restart
