---
- name: Install curl (required for GitLab Runner installation)
  apt:
    name: curl
    state: present

- name: Add GitLab Runner repository
  ansible.builtin.shell:
    cmd: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash

- name: Install GitLab Runner
  apt:
    name: gitlab-runner
    state: present

- name: Check if runner is already registered
  ansible.builtin.shell:
    cmd: gitlab-runner list | grep -q "[integration-server] docker"
  register: runner_registration_status
  failed_when: false
  changed_when: false

- name: Register GitLab Runner
  ansible.builtin.shell:
    cmd: >
      gitlab-runner register --non-interactive 
      --url "http://192.168.56.10/gitlab/" 
      --token "{{ runner_token }}" 
      --executor "docker" 
      --docker-image "alpine:latest" 
      --description "[integration-server] docker" 
      --tag-list "integration"
  become: yes
  when: runner_registration_status.rc != 0 and runner_token is defined and runner_token != 'YourGitlabRunnerTokenHere'
  tags: register_runner
  register: registration_result
  ignore_errors: yes

- name: Display registration error logs
  debug:
    msg: 
      - "STDOUT: {{ registration_result.stdout }}"
      - "STDERR: {{ registration_result.stderr }}"
  when: registration_result is failed and 'stdout' in registration_result and 'stderr' in registration_result

- name: Restart GitLab Runner
  ansible.builtin.shell:
    cmd: gitlab-runner restart
