stages:
  - build
  - test
  - deploy

variables:
  MYSQL_DATABASE: "e4l"
  MYSQL_ROOT_PASSWORD: ""  # Set your MYSQL root password

build:
  image: gradle:6.7.1-jdk8
  stage: build
  script:
    - gradle clean
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour
  only:
    - master

test:
  image: gradle:6.7.1-jdk8
  stage: test
  script:
    - gradle test
  only:
    - master

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache rsync
    - rsync -avz --delete ./build/libs/*.jar vagrant@192.168.56.11:/var/www/myapp/backend
  only:
    - master
